name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2        
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test 
      run: |
        ./gradlew build 
        ./gradlew test

    - name: Deploy Reports
      run: |
       eval $(ssh-agent -s -t 600) 
       ssh-add <(echo "${{ secrets.REPORTS_SSH_KEY }}")
       git config --global user.email "pspad001@odu.edu" 
       git config --global user.name "Project Actions"
       ./gradlew deployReports

      env:
        branch: gh-pages 
        folder: build/reports